theme: "blowfish" # UNCOMMENT THIS LINE
baseURL: 'https://togally.site/'
defaultContentLanguage: "zh-CN"

enableRobotsTXT: true
paginate: 10
summaryLength: 0

buildDrafts: false
buildFuture: false
enableEmoji: true

googleAnalytics: "G-MKRWGDMLP1"

imaging:
  anchor: 'Center'

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
  series: "series"

sitemap:
  changefreq: 'daily'
  filename: 'sitemap.xml'
  priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON