main:
  - name: 主页
    title: 鲸云🐳
    pageRef: /
    weight: 1
  - name: 分类
    title: 鲸云🐳的博客
    pageRef: categories
    weight: 2
  - name: 标签
    title: 鲸云🐳的博客
    pageRef: tags
    weight: 3
footer:
  - pre: github
    name: GitHub
    url: https://github.com/togally
    weight: 1